Address: "localhost:8090"
BaseURL: "/"
EmailConfig:
  Sender:
    ServerHost: "SERVER_HOST"
    ServerPort: 587
    SenderAddress: "ADDRESS@HOST"
    SenderName: "SENDER NAME"
    SenderPassword: "EMAIL_PASSWORD"
  Recipients:
    sales:
      Name: "Sales unit"
      Title: ""
      Address: "THEIR_EMAIL"
  Header:
    From: "ADDRESS@HOST"
    Subject: "SUBJECT?"
    MIME: "Content-Type: text/plain; charset=\"utf-8\"\nMIME-Version: 1.0"
    Miscellaneous: "Content-Transfer-Encoding: base64\n"
  TemplateText: |
    The NTC docs portal recieved a new issue from this sender:
    IP: {{ .IPAddress }}
    Name: {{ .FirstName }} {{ .LastName }}
    Product: {{ .ProductSerial }}-{{ .ProductModel }}
    Phone: {{ .PhoneNumber }}
    Company: {{ .CompanyName }}
    Reply Email Address: {{ .EmailAddress }}
    Issue Description: {{ .Description }}
